export {RestaurantLayout} from './RestaurantLayout'
export {RestaurantNewsletter} from './RestaurantNewsletter'
export {RestaurantMenu} from './RestaurantMenu'
export {RestaurantGallery} from './RestaurantGallery'
export { RestaurantInfo } from './RestaurantInfo'